#!/bin/sh

###############################################################################
# Required
###############################################################################
dotfilesrepo="git@github.com:alexb7711/dootfiles.git"
repobranch="main"
required_packages="curl ca-certificates build-essential git zsh dash stow ntp"

###############################################################################
# Optional
###############################################################################
nerd_fonts="SpaceMono" # Lists of fonts to install
